name: üöÄ Deployments of Microservices

env:
  SERVICE_NAME_SERVER: "college-ecosystem-server"

# on: workflow_dispatch

on:
  push:
    branches:
      - main
      - staging
      
  # workflow_dispatch:

concurrency:
  group:  ${{ github.workflow }}-${{ github.ref }}-servers-deploy
  cancel-in-progress: true
  
jobs:  

  deploy-mail-server:
    # needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: üì• Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: üîç Detect changed projects
        id: changed
        run: |
              git diff --quiet HEAD^ HEAD ./apps/mail-server || echo "mail_server_changed=true" >> $GITHUB_OUTPUT
      
      # - uses: pnpm/action-setup@v4

      - name: üõ†Ô∏è Setup Node.js
        uses: actions/setup-node@v4
        if: steps.changed.outputs.mail_server_changed == 'true'
        with:
          node-version: 20.x
          cache: "npm"

      - name: üíæ Cache Vercel CLI
        uses: actions/cache@v4
        if: steps.changed.outputs.mail_server_changed == 'true'
        with:
          path: ~/.vercel
          key: ${{ runner.os }}-vercel-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-vercel-

      - name: üì¶ Install Vercel CLI
        if: steps.changed.outputs.mail_server_changed == 'true'
        run: npm install -g vercel

      - name: üì≠ Deploy Mail Server to Production
        if: github.ref == 'refs/heads/main' && steps.changed.outputs.mail_server_changed == 'true'
        run: vercel --token ${{ secrets.VERCEL_TOKEN }} --prod ./apps/mail-server
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_MAIL_SERVER_PROJECT_ID }}

  dockerize-and-deploy-server:
    # needs: lint
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging' || github.event_name == 'workflow_dispatch'
    steps:
      - name: üì• Checkout repository
        uses: actions/checkout@v4

      - name: üîç Check changes in Server Directory
        id: server-changed
        run: |
          git diff --quiet HEAD^ HEAD ./apps/server || echo "server_changed=true" >> $GITHUB_OUTPUT
          git diff --quiet HEAD^ HEAD ./apps/server/Dockerfile || echo "dockerfile_changed=true" >> $GITHUB_OUTPUT

      - name: üîë Set up Google Cloud Auth SDK
        if: steps.server-changed.outputs.server_changed == 'true'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.CREDENTIALS_JSON }}
            
      - name: ‚öôÔ∏è Log in Docker to GCR
        if: steps.server-changed.outputs.server_changed == 'true'
        uses: docker/login-action@v2
        with:
            registry: gcr.io
            username: _json_key
            password:  ${{ secrets.CREDENTIALS_JSON }}
      
      - name: üê≥ Build and Push Docker Image
        if:  steps.server-changed.outputs.dockerfile_changed == 'true'
        run: |
          IMAGE_NAME="gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME_SERVER }}:latest"
          docker build --pull --rm -f "apps/server/Dockerfile" -t "${IMAGE_NAME}" "apps/server"
          docker push "${IMAGE_NAME}"

      - name: üöÄ Deploy to Cloud Run
        if: success()
        run: |  
          IMAGE_NAME="gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME_SERVER }}:latest"
          gcloud run deploy ${{ env.SERVICE_NAME_SERVER }} \
            --image "${IMAGE_NAME}" \
            --platform managed \
            --region ${{ secrets.GCP_PROJECT_REGION }} \
            --allow-unauthenticated

